name: Fly CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup latest Node.js LTS
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 'lts/*'
      - name: Setup Flyctl
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Setup service dependencies
        run: yarn install
      - name: Build service
        run: yarn build
      - name: Get Flyctl config
        env:
          FLY_CONFIG: ${{ secrets.FLY_CONFIG }}
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: base64 -d <<< "$FLY_CONFIG" > fly.toml
      - name: Publish service
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: flyctl deploy
